### ISSUE TITLE
Pattern pot incorrectly wired

### ISSUE THREAD

**Issue by craigyjp** [JuperTronic/Jupertronic_Perculator_Mini_Pops#1]
I was interested in adding this display to my existing mini pops Wee 03 build, but looking at the pattern pot you seem to have the center pin wired to +5v so when rotated you would effectively short +5v to ground. I know the pin numbering is correct but the pdf file connections are not. Maybe I'm wrong, but the pattern value will never change as it stands currently.

**Comment by JuperTronic** [comment]
Ahh yes, thank you for letting me know. As stated, I'm not a Fritzing wiz! I'll update that. Go by the hand drawing - center lug for signal of course.

**Comment by JuperTronic** [comment]
Okay, just updated the Fritz schem pdf. Thanks again for bringing that to my attention!

**Comment by craigyjp** [comment]
Thanks, just wanted to make sure before I added it to my build.
